spring:
#  application:
#    name: "food-service"

  datasource:
    url: jdbc:mysql://localhost:3306/jb2404?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "{cipher}7801b7f5847d2e8fb918dccd591f408dc2d4e3de4d8cbdf302168d5e2d99c4c9"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#    eureka configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
#
#
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true



